package main

// Emoji map to store name-emoji pairs
var EmojiMap = map[string]string{
	"smile":     "😄",
	"heart":     "❤️",
	"star":      "⭐",
	"thumbsup":  "👍",
	"rocket":    "🚀",
	"lightbulb": "💡",
	"checkmark": "✅",
	"warning":   "⚠️",
	"computer":  "💻",
	"books":     "📚",
	"fire":       "🔥",
	"clap":       "👏",
	"party":      "🎉",
	"coffee":     "☕",
	"sun":        "☀️",
	"moon":       "🌙",
	"cloud":      "☁️",
	"snowflake":  "❄️",
	"rainbow":    "🌈",
	"earth":      "🌍",
	"music":      "🎵",
	"dancer":     "💃",
	"runner":     "🏃‍♂️",
	"car":        "🚗",
	"airplane":   "✈️",
	"house":      "🏠",
	"phone":      "📱",
	"email":      "✉️",
	"moneybag":   "💰",
	"trophy":     "🏆",
	"soccerball": "⚽",
	"basketball":"🏀", 
	"dog":        "🐕",
	"cat":        "🐈",
	"fish":       "🐟",
	"bird":       "🐦",
	"lion":      "🦁",
	"tiger":      "🐅",
	"bear":       "🐻",
	"elephant":   "🐘",
	"giraffe":    "🦒",
	"zebra":      "🦓",
	"monkey":     "🐒",
	"panda":      "🐼",
	"koala":      "🐨",
	"whale":      "🐋",
	"octopus":    "🐙",
	"frog":       "🐸",
	"snail":      "🐌",
	"butterfly":  "🦋",
	"ladybug":    "🐞",
	"ant":        "🐜",
	"bee":        "🐝",
	"spider":     "🕷️",
	"scorpion":   "🦂",
	"dragon":     "🐉",
	"unicorn":    "🦄",
	"mermaid":    "🧜‍♀️",
	"fairy":      "🧚‍♀️",
	"vampire":    "🧛‍♂️",
	"zombie":     "🧟‍♂️",
	"ghost":      "👻",
	"alien":      "👽",
	"robot":      "🤖",
	"clown":      "🤡",
	"princess":   "👸",
	"prince":     "🤴",
	"king":       "👑",
	"queen":      "👸",
	"baby":       "👶",
	"child":      "👦",
	"adult":      "👨",
	"old":        "👴",
	"usa":       "🇺🇸",
	"canada":    "🇨🇦",
	"uk":        "🇬🇧",
	"france":    "🇫🇷",
	"germany":   "🇩🇪",
	"italy":     "🇮🇹",
	"spain":     "🇪🇸",
	"japan":     "🇯🇵",
	"china":     "🇨🇳",
	"india":     "🇮🇳",
	"australia": "🇦🇺",
	"brazil":    "🇧🇷",
	"southafrica":"🇿🇦",
	"mexico":    "🇲🇽",
	"southkorea":"🇰🇷",
	"russia":    "🇷🇺",
	"sweden":    "🇸🇪",
	"norway":    "🇳🇴",
	"finland":   "🇫🇮",
	"denmark":   "🇩🇰",
	"netherlands":"🇳🇱",
	"belgium":   "🇧🇪",
	"switzerland":"🇨🇭",
	"cherryblossom": "🌸", // Beauty, renewal, and spring
	"rose":          "🌹", // Love and romance
	"sunflower":     "🌻", // Happiness and positivity
	"tulip":         "🌷", // Grace and affection
	"hibiscus":      "🌺", // Tropical vibes and celebration
	"bouquet":       "💐", // Gratitude and congratulations
	"daisy":         "🌼", // Innocence and happiness
	"lotus":         "🪷", // Purity and enlightenment
	"rosette":       "🏵️", // Awards and achievements
	"wiltedflower":  "🥀", // Sadness or loss
}
